version: "3"
services: 
    mongo_1:
        image: "mongo" 
        logging:
            driver: "none"
    api:
        build: .
        depends_on: 
            - mongo_1
        ports:
            - "5000:5000"
        deploy:
            resources:
                limits:
                    memory: 8G